### ISSUE TITLE
Cannot execute server 2

### ISSUE THREAD

**Issue by distributev** [distributev/mailmerger#15]
![image](https://user-images.githubusercontent.com/19224635/39652254-3d0cf9cc-4fed-11e8-8feb-b1ed45b27725.png)

Then I tried various combinations in the DOS cmd prompt but still not luck - in the above screenshot you can see my folder structure

![image](https://user-images.githubusercontent.com/19224635/39652384-a1f914b0-4fed-11e8-9e0a-c2ee07155d66.png)

Please document both

1. How to run Server from Eclipse - detailed steps
2. How to run Server from DOS cmd  - so I can copy paste the working command

**Comment by p-bye** [comment]
Just tried this on Windows....

* Fresh clone of this repo into `c:\Projects\mailmerger`.
* `gradlew build` builds ok 👍 
* `gradlew shadowJar` to build the mailmerger-cmdline jar complete with dependencies to be used by the watch script.

Fresh install of Eclipse.  New workspace.  Import...
![screen shot 2018-05-05 at 19 51 13](https://user-images.githubusercontent.com/38662460/39666740-7c11eef8-50a0-11e8-92ed-7121312a332a.png)

Select the `c:\Projects\mailmerger` folder.  It should import successfully.

![screen shot 2018-05-05 at 19 51 53](https://user-images.githubusercontent.com/38662460/39666754-b90ed0dc-50a0-11e8-833a-f29586a2a5d9.png)

Verify you can run tests, etc.  e.g.

![screen shot 2018-05-05 at 19 52 31](https://user-images.githubusercontent.com/38662460/39666752-b25ffc20-50a0-11e8-8a6c-af7aed2d7545.png)

Right click the mailmerger-server Application and select Run.  It should run, but produce errors due to missing configuration.

![screen shot 2018-05-05 at 19 53 45](https://user-images.githubusercontent.com/38662460/39666763-f05d17e2-50a0-11e8-92d8-bf45df82d187.png)

Run Menu > Run Configurations...

![screen shot 2018-05-05 at 20 08 18](https://user-images.githubusercontent.com/38662460/39666765-fc31ce5a-50a0-11e8-8754-15b6fc6753f3.png)

Select the `watch` folder as the working directory.

I entered the following in the Program Arguments...

```
--project.dir=.
--watch.dir=../demo/watching
--completed.dir=../demo/complete
--config.file=default-configuration.xml
--mmJar=../mailmerger-cmdline/build/libs/mailmerger-cmdline-0.0.1-SNAPSHOT-all.jar
```

![screen shot 2018-05-05 at 20 08 38](https://user-images.githubusercontent.com/38662460/39666766-001d73c0-50a1-11e8-8610-5df1f2a4f84e.png)

Create a new folder called `demo` within the main `mailmerger` folder.  Then create `watching` and `complete` folders within the `demo` folder.

Run the Application within Eclipse.

![screen shot 2018-05-05 at 20 18 30](https://user-images.githubusercontent.com/38662460/39666803-84f78cac-50a1-11e8-8313-f95e6c2a6d03.png)

Put a file in the `c:\Projects\mailmerger\demo\watching` folder with contents
```
value1,value2,value3,value4
a,b,c,d
```

The file should get moved to the `complete` folder and you'll find a file in `c:\Projects\mailmerger\watch\outputfolder` called `a.pdf`

**Comment by distributev** [comment]
I got a step further but now I get this error

![image](https://user-images.githubusercontent.com/19224635/39689806-4e42264e-51d8-11e8-9fb2-cb59c99676b6.png)

![image](https://user-images.githubusercontent.com/19224635/39689846-6d4b711c-51d8-11e8-94c0-f6f1227a4c85.png)

**Comment by distributev** [comment]
I got it running by adding the below configuration in Eclipse - there is a watch folder in the home folder then I had to manually create a demo/watching folder - one the these too seems to be redundant - I like a little bit more consistency and a little bit of more "smart defaults" which tend to "just work" without adding manual configuration and worrying why I have 2 different watch and watching folders some of which I am requested to create manually.

![image](https://user-images.githubusercontent.com/19224635/39691131-d0d11882-51dc-11e8-9376-764e564101df.png)

![image](https://user-images.githubusercontent.com/19224635/39691175-efa1b9d8-51dc-11e8-9c59-e8e72a2e1aad.png)
