### ISSUE TITLE
errors while importing gradle project into eclipse

### ISSUE THREAD

**Issue by distributev** [distributev/mailmerger#2]
I tried to import the gradle project into eclipse and I get lots of "Classpath" errors

Importing should work out of the box without further manual Classpath modifications

![image](https://user-images.githubusercontent.com/19224635/39235105-4a15fb0c-4875-11e8-8d30-fcbbb83aff42.png)

**Comment by p-bye** [comment]
This is working for me (I had to add an additional JUnit dependency to get the tests to run within Eclipse)....

Using the latest version of Eclipse (Version: Oxygen.3a Release (4.7.3a))
<img width="452" alt="screen shot 2018-04-25 at 12 58 54" src="https://user-images.githubusercontent.com/38662460/39244736-7df0fb7a-4889-11e8-9686-af3c0713abc7.png">

<img width="282" alt="screen shot 2018-04-25 at 12 59 01" src="https://user-images.githubusercontent.com/38662460/39244744-82a0c5b0-4889-11e8-8b99-3aecd9d54edc.png">

I selected the mailmerger-cmdline project, otherwise Eclipse seems to attempt to import the submodule twice.

<img width="677" alt="screen shot 2018-04-25 at 12 59 41" src="https://user-images.githubusercontent.com/38662460/39244753-877c78d6-4889-11e8-872c-b0ded3c10895.png">

<img width="693" alt="screen shot 2018-04-25 at 13 00 03" src="https://user-images.githubusercontent.com/38662460/39244757-8c7ed93c-4889-11e8-9fbf-503363c61fe7.png">

<img width="520" alt="screen shot 2018-04-25 at 13 00 18" src="https://user-images.githubusercontent.com/38662460/39244762-9119256a-4889-11e8-888e-758b4a63fc6b.png">

**Comment by distributev** [comment]
I upgraded Eclipse from 4.7.0 to 4.7.3a and now it works fine.
